from sqlalchemy.orm import Session

from app.models.parking_session import ParkingSession
from app.models.parking_space import ParkingSpace
from app.models.vehicle import Vehicle
from app.models.whitelist_entry import WhitelistEntry
from app.services.billing_service import (
    PARKING_RATE_PER_MINUTE,
    apply_discount,
    calculate_parking_fee,
)
from app.services.time_service import pakistan_now


def payment_required_for_exit(db: Session, license_plate: str, billing_enabled: bool) -> bool:
    if not billing_enabled:
        return False

    vehicle = db.query(Vehicle).filter(Vehicle.license_plate == license_plate.strip().upper()).first()
    if vehicle is None:
        raise ValueError("Vehicle not found")

    session = db.query(ParkingSession).filter(
        ParkingSession.vehicle_id == vehicle.id,
        ParkingSession.status == "active",
    ).first()
    if session is None:
        raise ValueError("No active parking session found")

    amount, _ = calculate_parking_fee(session.entry_time, pakistan_now())
    whitelist_entry = db.query(WhitelistEntry).filter(
        WhitelistEntry.license_plate == vehicle.license_plate
    ).first()
    discount_percent = whitelist_entry.discount_percent if whitelist_entry else 0
    return apply_discount(amount, discount_percent) > 0


def process_vehicle_exit_by_plate(
    db: Session,
    license_plate: str,
    payment_method: str | None,
    billing_enabled: bool = True,
):
    """
    Complete the active parking session for a license
    plate recognized by the CV system.
    """

    license_plate = license_plate.strip().upper()

    if not license_plate:
        raise ValueError("License plate was not recognized")

    vehicle = db.query(Vehicle).filter(Vehicle.license_plate == license_plate).first()

    if vehicle is None:
        raise ValueError("Vehicle not found")

    session = (
        db.query(ParkingSession)
        .filter(
            ParkingSession.vehicle_id == vehicle.id,
            ParkingSession.status == "active",
        )
        .first()
    )

    if session is None:
        raise ValueError("No active parking session found")

    return complete_parking_session(
        db=db,
        session=session,
        vehicle=vehicle,
        payment_method=payment_method,
        billing_enabled=billing_enabled,
    )


def complete_parking_session(
    db: Session,
    session: ParkingSession,
    vehicle: Vehicle,
    payment_method: str | None,
    billing_enabled: bool = True,
):
    """
    Complete an active parking session.

    Exit time and parking fee are generated by the backend.
    """

    exit_time = pakistan_now()

    if billing_enabled:
        amount, billed_minutes = calculate_parking_fee(
            session.entry_time,
            exit_time,
        )

        whitelist_entry = (
            db.query(WhitelistEntry)
            .filter(WhitelistEntry.license_plate == vehicle.license_plate)
            .first()
        )
        discount_percent = whitelist_entry.discount_percent if whitelist_entry else 0
        amount = apply_discount(amount, discount_percent)
    else:
        amount = 0.0
        billed_minutes = 0
        discount_percent = 0

    session.exit_time = exit_time
    session.amount = amount
    session.payment_method = payment_method
    session.status = "completed"

    parking_space = (
        db.query(ParkingSpace)
        .filter(ParkingSpace.id == session.parking_space_id)
        .first()
    )

    if parking_space is None:
        db.rollback()
        raise ValueError("Parking space associated with session was not found")

    parking_space.is_occupied = False

    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    db.refresh(session)

    return {
        "session_id": session.id,
        "license_plate": vehicle.license_plate,
        "entry_time": session.entry_time,
        "exit_time": session.exit_time,
        "duration_minutes": billed_minutes,
        "rate_per_minute": PARKING_RATE_PER_MINUTE,
        "amount": session.amount,
        "discount_percent": discount_percent,
        "payment_method": session.payment_method,
        "billing_enabled": billing_enabled,
        "level": parking_space.level,
        "space": parking_space.space_number,
        "status": session.status,
    }
