from sqlalchemy.orm import Session

from app.models.parking_session import ParkingSession
from app.models.parking_space import ParkingSpace
from app.models.vehicle import Vehicle
from app.services.billing_service import (
    PARKING_RATE_PER_MINUTE,
    calculate_parking_fee,
)
from app.services.time_service import pakistan_now


def process_vehicle_exit_by_plate(
    db: Session,
    license_plate: str,
    payment_method: str,
):
    """
    Complete the active parking session for a license
    plate recognized by the CV system.
    """

    license_plate = license_plate.strip().upper()

    if not license_plate:
        raise ValueError("License plate was not recognized")

    vehicle = db.query(Vehicle).filter(Vehicle.license_plate == license_plate).first()

    if vehicle is None:
        raise ValueError("Vehicle not found")

    session = (
        db.query(ParkingSession)
        .filter(
            ParkingSession.vehicle_id == vehicle.id,
            ParkingSession.status == "active",
        )
        .first()
    )

    if session is None:
        raise ValueError("No active parking session found")

    return complete_parking_session(
        db=db,
        session=session,
        vehicle=vehicle,
        payment_method=payment_method,
    )


def complete_parking_session(
    db: Session,
    session: ParkingSession,
    vehicle: Vehicle,
    payment_method: str,
):
    """
    Complete an active parking session.

    Exit time and parking fee are generated by the backend.
    """

    exit_time = pakistan_now()

    amount, billed_minutes = calculate_parking_fee(
        session.entry_time,
        exit_time,
    )

    session.exit_time = exit_time
    session.amount = amount
    session.payment_method = payment_method
    session.status = "completed"

    parking_space = (
        db.query(ParkingSpace)
        .filter(ParkingSpace.id == session.parking_space_id)
        .first()
    )

    if parking_space is None:
        db.rollback()
        raise ValueError("Parking space associated with session was not found")

    parking_space.is_occupied = False

    try:
        db.commit()
    except Exception:
        db.rollback()
        raise

    db.refresh(session)

    return {
        "session_id": session.id,
        "license_plate": vehicle.license_plate,
        "entry_time": session.entry_time,
        "exit_time": session.exit_time,
        "duration_minutes": billed_minutes,
        "rate_per_minute": PARKING_RATE_PER_MINUTE,
        "amount": session.amount,
        "payment_method": session.payment_method,
        "level": parking_space.level,
        "space": parking_space.space_number,
        "status": session.status,
    }
