from sqlalchemy.orm import Session

from app.models.parking_session import ParkingSession
from app.models.parking_space import ParkingSpace
from app.models.vehicle import Vehicle
from app.models.whitelist_entry import WhitelistEntry
from app.services.billing_service import (
    PARKING_RATE_PER_MINUTE,
    apply_discount,
    calculate_parking_fee,
)
from app.services.time_service import pakistan_now


def payment_required_for_exit(
    db: Session,
    license_plate: str,
    billing_enabled: bool,
    tenant_id: int,
    rate_per_minute: float = PARKING_RATE_PER_MINUTE,
    rate_unit: str = "minute",
) -> bool:
    if not billing_enabled:
        return False

    vehicle = (
        db.query(Vehicle)
        .filter(
            Vehicle.tenant_id == tenant_id,
            Vehicle.license_plate == license_plate.strip().upper(),
        )
        .first()
    )

    if vehicle is None:
        raise ValueError("Vehicle not found")

    session = (
        db.query(ParkingSession)
        .filter(
            ParkingSession.vehicle_id == vehicle.id,
            ParkingSession.tenant_id == tenant_id,
            ParkingSession.status == "active",
        )
        .first()
    )

    if session is None:
        raise ValueError("This vehicle is not parked in the garage.")

    amount, _ = calculate_parking_fee(
        session.entry_time,
        pakistan_now(),
        rate_per_minute,
        rate_unit,
    )

    whitelist_entry = (
        db.query(WhitelistEntry)
        .filter(
            WhitelistEntry.license_plate == vehicle.license_plate,
            WhitelistEntry.tenant_id == tenant_id,
        )
        .first()
    )

    discount_percent = whitelist_entry.discount_percent if whitelist_entry else 0

    return (
        apply_discount(
            amount,
            discount_percent,
        )
        > 0
    )


def process_vehicle_exit_by_plate(
    db: Session,
    license_plate: str,
    payment_method: str | None,
    billing_enabled: bool = True,
    rate_per_minute: float = PARKING_RATE_PER_MINUTE,
    rate_unit: str = "minute",
    tenant_id: int | None = None,
):
    """
    Complete the active parking session for a license
    plate recognized by the CV system.
    """

    license_plate = license_plate.strip().upper()

    if not license_plate:
        raise ValueError("License plate was not recognized")

    vehicle = (
        db.query(Vehicle)
        .filter(
            Vehicle.tenant_id == tenant_id,
            Vehicle.license_plate == license_plate,
        )
        .first()
    )

    if vehicle is None:
        raise ValueError("Vehicle not found")

    session = (
        db.query(ParkingSession)
        .filter(
            ParkingSession.vehicle_id == vehicle.id,
            ParkingSession.tenant_id == tenant_id,
            ParkingSession.status == "active",
        )
        .first()
    )

    if session is None:
        raise ValueError("No active parking session found")

    return complete_parking_session(
        db=db,
        session=session,
        vehicle=vehicle,
        payment_method=payment_method,
        billing_enabled=billing_enabled,
        rate_per_minute=rate_per_minute,
        rate_unit=rate_unit,
        tenant_id=tenant_id,
    )


def complete_parking_session(
    db: Session,
    session: ParkingSession,
    vehicle: Vehicle,
    payment_method: str | None,
    billing_enabled: bool = True,
    rate_per_minute: float = PARKING_RATE_PER_MINUTE,
    rate_unit: str = "minute",
    tenant_id: int | None = None,
):
    """
    Complete an active parking session.

    Exit time and parking fee are generated by the backend.
    """

    exit_time = pakistan_now()

    # ============================================================
    # Calculate payment
    # ============================================================

    if billing_enabled:
        amount, billed_minutes = calculate_parking_fee(
            session.entry_time,
            exit_time,
            rate_per_minute,
            rate_unit,
        )

        whitelist_entry = (
            db.query(WhitelistEntry)
            .filter(
                WhitelistEntry.license_plate == vehicle.license_plate,
                WhitelistEntry.tenant_id == tenant_id,
            )
            .first()
        )

        discount_percent = whitelist_entry.discount_percent if whitelist_entry else 0

        amount = apply_discount(
            amount,
            discount_percent,
        )

    else:
        amount = 0.0
        billed_minutes = 0
        discount_percent = 0

    # ============================================================
    # Complete session
    # ============================================================

    session.exit_time = exit_time
    session.amount = amount
    session.discount_percent = discount_percent
    session.payment_method = payment_method
    session.status = "completed"

    # ============================================================
    # Find associated parking space
    # ============================================================

    parking_space = None

    if session.parking_space_id is not None:
        parking_space = (
            db.query(ParkingSpace)
            .filter(
                ParkingSpace.id == session.parking_space_id,
                ParkingSpace.tenant_id == tenant_id,
            )
            .with_for_update()
            .first()
        )

    # ============================================================
    # Safely recalculate occupancy
    # ============================================================

    if parking_space:

        other_active_session = (
            db.query(ParkingSession.id)
            .filter(
                ParkingSession.parking_space_id == parking_space.id,
                ParkingSession.tenant_id == tenant_id,
                ParkingSession.status == "active",
                ParkingSession.id != session.id,
            )
            .first()
        )

        parking_space.is_occupied = other_active_session is not None

    # ============================================================
    # Commit transaction
    # ============================================================

    try:
        db.flush()
        db.commit()

    except Exception:
        db.rollback()
        raise

    # ============================================================
    # Refresh committed objects
    # ============================================================

    db.refresh(session)

    if parking_space:
        db.refresh(parking_space)

    # ============================================================
    # Response
    # ============================================================

    return {
        "session_id": session.id,
        "license_plate": vehicle.license_plate,
        "entry_time": session.entry_time,
        "exit_time": session.exit_time,
        "duration_minutes": billed_minutes,
        "rate_per_minute": rate_per_minute,
        "rate_unit": rate_unit,
        "amount": session.amount,
        "discount_percent": discount_percent,
        "payment_method": session.payment_method,
        "billing_enabled": billing_enabled,
        "level": parking_space.level if parking_space else None,
        "space": parking_space.space_number if parking_space else None,
        "status": session.status,
    }
